### ISSUE TITLE
Выдает 2 ошибки в parser_cls

### ISSUE THREAD

**Issue by mrmmm88** [Duff89/parser_avito#10]
добрый день.
если запускать через AvitoParser то показывает: 
2023-06-04 03:39:36.959 | INFO     | __main__:logger_widget_init:230 - Запуск AvitoParser
2023-06-04 03:39:36.964 | INFO     | __main__:logger_widget_init:231 - Чтобы начать работу, проверьте, чтобы поле URL было заполненными, остальное на Ваше усмотрение. Нужна помощь - нажмите на ссылку внизу окна.
2023-06-04 03:39:36.994 | INFO     | __main__:logger_widget_init:233 - Удачного поиска !!!
2023-06-04 03:39:46.137 | INFO     | __main__:start_scraping:139 - Начинаем поиск
2023-06-04 03:39:46.164 | ERROR    | parser_cls:parse:254 - Ошибка: '<' not supported between instances of 'str' and 'int'
Exception in thread Thread-1 (start_scraping):
Traceback (most recent call last):
  File "C:\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\79537\Desktop\ollpython\авито парсер\AvitoParser.py", line 150, in start_scraping
    self.run_parse()
  File "C:\Users\79537\Desktop\ollpython\авито парсер\AvitoParser.py", line 255, in run_parse
    ).parse()
      ^^^^^^^
  File "C:\Users\79537\Desktop\ollpython\авито парсер\parser_cls.py", line 256, in parse
    self.driver.quit()
    ^^^^^^^^^^^
AttributeError: 'AvitoParse' object has no attribute 'driver'

если parser_cls запускаю: 
2023-06-04 03:51:01.054 | ERROR    | __main__:parse:254 - Ошибка: '<' not supported between instances of 'str' and 'int'
2023-06-04 03:51:01.054 | ERROR    | __main__:<module>:296 - 'AvitoParse' object has no attribute 'driver'
2023-06-04 03:51:01.055 | ERROR    | __main__:<module>:297 - Произошла ошибка, но работа будет продолжена через 30 сек. Если ошибка повторится несколько раз - перезапустите скрипт.Если и это не поможет - обратитесь к разработчику
по ошибке int-str  сравнение на 121-127 строчке   мин-мах прайс с прайсом взятым с авито но там все в str переведено больше не где не нашел.
по драйверу тоже вроде все прописано.
снес установил все заново - тоже самое.

**Comment by Duff89** [comment]
Эта ошибка возникает из-за версии Chrome, решение проблемы [https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1252](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1252) , вызывается Chrome в parser.cls, строка 46.
Поправлю этот момент в следующей версии

**Comment by mrmmm88** [comment]
Я к сожалению так и не понял каких изменений требует 46 строка,если не сложно можете исправленный вариант строки написать

**Comment by Duff89** [comment]
def __set_up(self):
        options = Options()
        
        options.add_argument("--headless=chrome") # или так
        #options.add_argument("--headless=new") # или так

        _ua = choice(list(map(str.rstrip, open("user_agent_pc.txt").readlines())))
        options.add_argument(f'--user-agent={_ua}')
        self.driver = uc.Chrome(version_main=self.__get_chrome_version,
                                options=options,
                                )

Вот переписанный метод. Обратите внимание на две строки: options.add_argument("--headless=chrome")  и options.add_argument("--headless=new") . Должна работать только одна строка, вторая(или первая) должна быть закомментирована

**Comment by Duff89** [comment]
В связи с выходом новой версии закрываю проблему
