### ISSUE TITLE
Ошибка An error has been caught in function '__paginator'

### ISSUE THREAD

**Issue by 1337CTPAHHIK** [Duff89/parser_avito#15]
После нажатия кнопки "Старт" происходит ошибка, при этом обычно 1-2 объявления по запросу выдает.
Прилагаю:

`2023-06-18 20:12:45.482 | ERROR    | parser_cls:__paginator:79 - An error has been caught in function '__paginator', process 'MainProcess' (6476), thread 'Thread-2 (start_scraping)' (6884):
Traceback (most recent call last):

  File "C:\Users\CTPAHHIK\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000254CB59E0C0>
    └ <Thread(Thread-2 (start_scraping), started 6884)>
  File "C:\Users\CTPAHHIK\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000254CB59DDA0>
    └ <Thread(Thread-2 (start_scraping), started 6884)>
  File "C:\Users\CTPAHHIK\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2 (start_scraping), started 6884)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-2 (start_scraping), started 6884)>
    │    └ <bound method Window.start_scraping of <__main__.Window object .>>
    └ <Thread(Thread-2 (start_scraping), started 6884)>

  File "C:\Users\CTPAHHIK\Desktop\parser_avito-master\AvitoParser.py", line 150, in start_scraping
    self.run_parse()
    │    └ <function Window.run_parse at 0x00000254CED396C0>
    └ <__main__.Window object .>

  File "C:\Users\CTPAHHIK\Desktop\parser_avito-master\AvitoParser.py", line 255, in run_parse
    ).parse()

  File "C:\Users\CTPAHHIK\Desktop\parser_avito-master\parser_cls.py", line 252, in parse
    self.__paginator()
    └ <parser_cls.AvitoParse object at 0x00000254CED4B550>

> File "C:\Users\CTPAHHIK\Desktop\parser_avito-master\parser_cls.py", line 79, in __paginator
    self.__parse_page()
    └ <parser_cls.AvitoParse object at 0x00000254CED4B550>

  File "C:\Users\CTPAHHIK\Desktop\parser_avito-master\parser_cls.py", line 126, in __parse_page
    self.__save_data(data=data)
    │                     └ {'name': 'ВАЗ (LADA) 2110, 2005', 'description': 'Доставка автомобилей в другие регионы, до границ Днр и Лнр бесплатно, уточн...
    └ <parser_cls.AvitoParse object at 0x00000254CED4B550>

  File "C:\Users\CTPAHHIK\Desktop\parser_avito-master\parser_cls.py", line 189, in __save_data
    writer.writerow([
    │      └ <method 'writerow' of '_csv.writer' objects>
    └ <_csv.writer object at 0x00000254CEB4D240>

  File "C:\Users\CTPAHHIK\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           │      │              │     │    │      └ <EncodingMap object at 0x00000254CAB82510>
           │      │              │     │    └ 'strict'
           │      │              │     └ <encodings.cp1251.IncrementalEncoder object at 0x00000254CEDAA290>
           │      │              └ '"ВАЗ (LADA) 2110, 2005",135000,https://www.avito.ru/novocherkassk/avtomobili/vaz_lada_2110_2005_2999389184,"Доставка автомоб...
           │      └ <built-in function charmap_encode>
           └ <module 'codecs' (frozen)>

UnicodeEncodeError: 'charmap' codec can't encode character '\u2033' in position 1997: character maps to <undefined>
2023-06-18 20:12:47.527 | INFO     | __main__:start_scraping:152 - Проверка завершена
2023-06-18 20:12:47.536 | INFO     | __main__:start_scraping:153 - Пауза 5 минут
2023-06-18 20:13:57.574 | INFO     | __main__:stop_scraping:175 - Идет остановка. Пожалуйста, подождите
2023-06-18 20:13:57.700 | INFO     | __main__:start_scraping:160 - Успешно остановлено
`

**Comment by Duff89** [comment]
проблема известная. Решение здесь #7

**Comment by Duff89** [comment]
В связи с выходом новой версии закрываю проблему
