### ISSUE TITLE
configparser.InterpolationSyntaxError: '%' must be followed by '%'

### ISSUE THREAD

**Issue by Autolocsia** [Duff89/parser_avito#19]
Авито при указании радиуса добавляет координаты и получается ссылка вида: 

https://www.avito.ru/sevastopol/bytovaya_tehnika/dlya_doma/stiralnye_mashiny-ASgBAgICAkRgpE_OB6ZP?cd=1&geoCoords=44.616687%2C33.525432&localPriority=0&radius=50&s=104

При таком виде ошибка:

Traceback (most recent call last):
  File "/parser_avito-master/parser_cls.py", line 256, in <module>
    url = config["Avito"]["URL"]
  File "/usr/lib/python3.10/configparser.py", line 1259, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.10/configparser.py", line 800, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.10/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.10/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2C33.525432&localPriority=0&radius=50&s=104'

**Comment by Duff89** [comment]
> 

Попробовал запустить с таким url у себя - всё ок, работает.
Понятно, что ошибка в Вашем случае возникает из-за символа %. Попробуйте просто вручную убрать данный символ из url

**Comment by Autolocsia** [comment]
![Снимок экрана от 2023-07-19 19-28-45](https://github.com/Duff89/parser_avito/assets/43119424/059d8526-a43c-4228-8da6-8e49bd10c1ce)
![Снимок экрана от 2023-07-19 19-29-06](https://github.com/Duff89/parser_avito/assets/43119424/1eda1d0f-fc62-4c34-a1bf-76e559150418)
![Снимок экрана от 2023-07-19 19-29-52](https://github.com/Duff89/parser_avito/assets/43119424/5290db2a-461c-4bfb-baaa-06a1f311c154)

Стоит нажать радиус, скопировать - вставить и не работает парсер, а без % работает парсер, но не работает поиск по радиусу тогда

Может из-за того что я запускаю через python3? Просто через python не запускается

**Comment by Duff89** [comment]
У Вас питон 3.10, с версией всё ок.
А попробуйте url каждый раз вставлять самостоятельно в окно программы.
-Т.е. сейчас сотрите в settings.ini этот адрес
-Запустите парсер,поле с url должно быть пустым, вставьте url и нажмите Старт

**Comment by Autolocsia** [comment]
Интересно, я стер в settings.ini значение url - запустил AvitoParser.py и ввел тот же адрес с % туда и все работает, но есть одно но, в settings.ini записалось с двумя %%, а не одной

**Comment by Autolocsia** [comment]
Буду теперь знать, что в settings.ini вручную нужно добавлять будет еще один %

**Comment by Duff89** [comment]
Это особенности экранирования в python. Постараюсь исправить в следующей версии

**Comment by Autolocsia** [comment]
p.s. было бы не плохо добавить еще какой-то способ доната вам, какая-то комиссия жестокая за 25р взяло еще + 50.50р комисии, шок О_о (хорошо, что небольшую сумму попробовал)
