### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '

### ISSUE THREAD

**Issue by NikitaTsekh** [Duff89/parser_avito#20]
![image](https://github.com/Duff89/parser_avito/assets/98738510/fe16db34-660f-43ba-a903-ea795d7c3a31)

(venv) nikita@nikita-ubuntu:~/VS_Code_Projects/AvitoParser/parser_avito$ python3 AvitoParser.py 
2023-07-16 21:27:56.946 | INFO     | __main__:logger_widget_init:233 - Запуск AvitoParser
2023-07-16 21:27:56.949 | INFO     | __main__:logger_widget_init:234 - Чтобы начать работу, проверьте, чтобы поле URL было заполненными, остальное на Ваше усмотрение. Нужна помощь - нажмите на ссылку внизу окна.
2023-07-16 21:27:56.954 | INFO     | __main__:logger_widget_init:236 - Удачного поиска !!!
2023-07-16 21:28:44.241 | INFO     | __main__:logger_tg:225 - Данные для отправки в telegram не заполнены. Результат будет сохранен в файл и выведен здесь
2023-07-16 21:28:44.242 | INFO     | __main__:telegram_log_test:124 - Должны быть заполнены поля ТОКЕН TELEGRAM и CHAT ID TELEGRAM
2023-07-16 21:28:48.023 | INFO     | __main__:logger_tg:225 - Данные для отправки в telegram не заполнены. Результат будет сохранен в файл и выведен здесь
2023-07-16 21:28:48.044 | INFO     | __main__:start_scraping:141 - Начинаем поиск
Exception in thread Thread-1 (start_scraping):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nikita/VS_Code_Projects/AvitoParser/parser_avito/AvitoParser.py", line 152, in start_scraping
    self.run_parse()
  File "/home/nikita/VS_Code_Projects/AvitoParser/parser_avito/AvitoParser.py", line 256, in run_parse
    max_price=int(max_price),
ValueError: invalid literal for int() with base 10: ''

**Comment by Duff89** [comment]
> ![image](https://user-images.githubusercontent.com/98738510/253820869-fe16db34-660f-43ba-a903-ea795d7c3a31.png)
> 
> (venv) nikita@nikita-ubuntu:~/VS_Code_Projects/AvitoParser/parser_avito$ python3 AvitoParser.py 2023-07-16 21:27:56.946 | INFO | **main**:logger_widget_init:233 - Запуск AvitoParser 2023-07-16 21:27:56.949 | INFO | **main**:logger_widget_init:234 - Чтобы начать работу, проверьте, чтобы поле URL было заполненными, остальное на Ваше усмотрение. Нужна помощь - нажмите на ссылку внизу окна. 2023-07-16 21:27:56.954 | INFO | **main**:logger_widget_init:236 - Удачного поиска !!! 2023-07-16 21:28:44.241 | INFO | **main**:logger_tg:225 - Данные для отправки в telegram не заполнены. Результат будет сохранен в файл и выведен здесь 2023-07-16 21:28:44.242 | INFO | **main**:telegram_log_test:124 - Должны быть заполнены поля ТОКЕН TELEGRAM и CHAT ID TELEGRAM 2023-07-16 21:28:48.023 | INFO | **main**:logger_tg:225 - Данные для отправки в telegram не заполнены. Результат будет сохранен в файл и выведен здесь 2023-07-16 21:28:48.044 | INFO | **main**:start_scraping:141 - Начинаем поиск Exception in thread Thread-1 (start_scraping): Traceback (most recent call last): File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner self.run() File "/usr/lib/python3.10/threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "/home/nikita/VS_Code_Projects/AvitoParser/parser_avito/AvitoParser.py", line 152, in start_scraping self.run_parse() File "/home/nikita/VS_Code_Projects/AvitoParser/parser_avito/AvitoParser.py", line 256, in run_parse max_price=int(max_price), ValueError: invalid literal for int() with base 10: ''

Наверное стоит заполнить поле максимальная цена
