### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by TemArt90** [Duff89/parser_avito#21]
![image](https://github.com/Duff89/parser_avito/assets/52446026/8cdfaaf6-9c20-465b-9206-b44c90d7ae38)

Exception in thread Thread-1 (start_scraping):
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/temart/parser_avito/AvitoParser.py", line 152, in start_scraping
    self.run_parse()
  File "/home/temart/parser_avito/AvitoParser.py", line 258, in run_parse
    ).parse()
      ^^^^^^^
  File "/home/temart/parser_avito/parser_cls.py", line 236, in parse
    with SB(uc=True,
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/plugins/sb_manager.py", line 815, in SB
    sb.setUp()
  File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/fixtures/base_case.py", line 13825, in setUp
    self.driver = self.get_new_driver(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/fixtures/base_case.py", line 3783, in get_new_driver
    new_driver = browser_launcher.get_driver(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1234, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3044, in get_local_driver
    driver = undetected.Chrome(
             ^^^^^^^^^^^^^^^^^^
  File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 294, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1824, in _execute_child
    and os.path.dirname(executable)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Duff89** [comment]
> ![image](https://user-images.githubusercontent.com/52446026/254618605-8cdfaaf6-9c20-465b-9206-b44c90d7ae38.png)
> 
> Exception in thread Thread-1 (start_scraping): Traceback (most recent call last): File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner self.run() File "/usr/lib64/python3.11/threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "/home/temart/parser_avito/AvitoParser.py", line 152, in start_scraping self.run_parse() File "/home/temart/parser_avito/AvitoParser.py", line 258, in run_parse ).parse() ^^^^^^^ File "/home/temart/parser_avito/parser_cls.py", line 236, in parse with SB(uc=True, File "/usr/lib64/python3.11/contextlib.py", line 137, in **enter** return next(self.gen) ^^^^^^^^^^^^^^ File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/plugins/sb_manager.py", line 815, in SB sb.setUp() File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/fixtures/base_case.py", line 13825, in setUp self.driver = self.get_new_driver( ^^^^^^^^^^^^^^^^^^^^ File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/fixtures/base_case.py", line 3783, in get_new_driver new_driver = browser_launcher.get_driver( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1234, in get_driver return get_local_driver( ^^^^^^^^^^^^^^^^^ File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3044, in get_local_driver driver = undetected.Chrome( ^^^^^^^^^^^^^^^^^^ File "/home/temart/parser_avito/env/lib64/python3.11/site-packages/seleniumbase/undetected/**init**.py", line 294, in **init** browser = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "/usr/lib64/python3.11/subprocess.py", line 1026, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib64/python3.11/subprocess.py", line 1824, in _execute_child and os.path.dirname(executable) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 152, in dirname TypeError: expected str, bytes or os.PathLike object, not NoneType

У Вас установлен Chrome?

**Comment by Duff89** [comment]
Нет ответа
