### ISSUE TITLE
При запуске появляется командная строка с ошибкой в ней Неверно задано имя папки. Отказано в доступе.

### ISSUE THREAD

**Issue by lp85d** [Duff89/parser_avito#32]
Что я делал:
1. **Установил** [python-3.11.4-amd64](https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe)
2. Пробросил **переменные среды**  C:\Users\avito\AppData\Local\Programs\Python\Python311\Scripts\
3. **Установил** библиотеку _pip install undetected-chromedriver_
4. Установил все **зависимости** _​C:\Users\avito\AppData\Local\Programs\Python\Python311\python.exe -m pip install -r C:\Users\avito\Desktop\parser_avito-master\requirements.txt_
5. При запуске программы _C:\Users\avito\Desktop\parser_avito-master\AvitoParser.py_
Получаю ошибку:
_Неверно задано имя папки.
c:\progra ~ 1\common~1\system\symsrv.dll.000
Отказано в доступе._
И в папке с программой появилась папка с файлами
C:\Users\avito\Desktop\parser_avito-master\__pycache__\locator.cpython-311.pyc
C:\Users\avito\Desktop\parser_avito-master\__pycache__\parser_cls.cpython-311.pyc

**Comment by lp85d** [comment]
Проблему получилось решить после замены параметра: **num_ads** = 1
C:\Users\avito\Desktop\parser_avito-master\settings.ini
![image](https://github.com/Duff89/parser_avito/assets/3320759/d92a8af1-5b99-4963-8025-ccec17a99730)

**Comment by lp85d** [comment]
Но как видим в окне программы выводится Р+/Сг вместо б/у
Кодировку использую UTF-8

**Comment by lp85d** [comment]
Сообщение по кнопке TEST не пришло
`2023-08-21 21:09:34.450 | INFO     | __main__:logger_widget_init:225 - Запуск AvitoParser
2023-08-21 21:09:34.455 | INFO     | __main__:logger_widget_init:226 - Чтобы начать работу, проверьте, чтобы поле URL было заполненными, остальное на Ваше усмотрение. Нужна помощь - нажмите на ссылку внизу окна.
2023-08-21 21:09:34.476 | INFO     | __main__:logger_widget_init:228 - Удачного поиска !!!
2023-08-21 21:09:49.069 | SUCCESS  | __main__:telegram_log_test:113 - test
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\notifiers\logging.py", line 50, in emit    self.provider.notify(raise_on_errors=True, **data)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\notifiers\core.py", line 306, in notify    rsp.raise_on_errors()
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\notifiers\core.py", line 60, in raise_on_errors
    raise NotificationError(
notifiers.exceptions.NotificationError: Notification errors: Bad Request: chat not found
Call stack:
  File "C:\Users\avito\Desktop\parser_avito-master\AvitoParser.py", line 268, in <module>
    Window().mainloop()
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 163, in mainloop
    super().mainloop(*args, **kwargs)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\avito\Desktop\parser_avito-master\AvitoParser.py", line 113, in telegram_log_test
    logger.success('test')
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\loguru\_logger.py", line 2018, in success
    __self._log("SUCCESS", False, __self._options, __message, args, kwargs)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\loguru\_logger.py", line 2002, in _log
    handler.emit(log_record, level_id, from_decorator, raw, colored_message)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\loguru\_handler.py", line 197, in emit
    self._sink.write(str_record)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\loguru\_simple_sinks.py", line 50, in write
    self._handler.handle(record)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 978, in handle
    self.emit(record)
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\notifiers\logging.py", line 52, in emit    self.handleError(record)
Message: 'test'
Arguments: ()
2023-08-21 21:09:51.884 | INFO     | __main__:telegram_log_test:115 - Если сообщение пришло к Вам в telegram - значит всё настроено правильно. Если нет - результат парсинга всегда можно посмотреть в папке result или ниже

`

**Comment by lp85d** [comment]
Exception in thread Thread-1 (start_scraping):
Traceback (most recent call last):
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 3074, in get_local_driver
    driver = undetected.Chrome(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\undetected\__init__.py", line 277, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 14001] Не удалось запустить приложение, поскольку его параллельная конфигурация неправильна. Дополнительные сведения содержатся в журнале событий приложений или используйте программу командной строки sxstrace.exe для получения дополнительных сведений

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\avito\Desktop\parser_avito-master\AvitoParser.py", line 146, in start_scraping
    self.run_parse()
  File "C:\Users\avito\Desktop\parser_avito-master\AvitoParser.py", line 250, in run_parse
    ).parse()
      ^^^^^^^
  File "C:\Users\avito\Desktop\parser_avito-master\parser_cls.py", line 236, in parse
    with SB(uc=True,
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\plugins\sb_manager.py", line 815, in SB
    sb.setUp()
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\fixtures\base_case.py", line 13915, in setUp
    self.driver = self.get_new_driver(
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\fixtures\base_case.py", line 3818, in get_new_driver
    new_driver = browser_launcher.get_driver(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 1261, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 3385, in get_local_driver
    return webdriver.Chrome()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 51, in __init__
    self.service.start()
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 97, in start
    self.assert_process_still_running()
  File "C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 110, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service C:\Users\avito\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\drivers\chromedriver.EXE unexpectedly exited. Status code was: 3221225477

**Comment by lp85d** [comment]
**Разобрался**, чтобы бот TgmParsBOT выдал сообщение нужно было его запустить в том профиле куда отправляю test
Ну и всё ошибки нет 👍
![image](https://github.com/Duff89/parser_avito/assets/3320759/1658be75-1379-4cf9-874e-318237e71bc9)

**Comment by lp85d** [comment]
![image](https://github.com/Duff89/parser_avito/assets/3320759/99a1df80-ebc3-472d-93cc-0f589d1609a6)

**Comment by lp85d** [comment]
Программу закрыл и процесс **запустился**!!!
![image](https://github.com/Duff89/parser_avito/assets/3320759/bd595af2-6a8a-4f76-9140-3ff4aa5fc630)

**Comment by lp85d** [comment]
Проблема в том что программу закрываю и начинается запускаться и то с ошибками, как я понимаю ему хром 114 нужен?

**Comment by lp85d** [comment]
Ок буду искать способ откатится на 114 версию, спасибо
