### ISSUE TITLE
Переодическая ошибка

### ISSUE THREAD

**Issue by 1scrooge** [Duff89/parser_avito#45]
Переодически вылетает такая ошибка, но парсер продолжает работать. Это на что нибудь аффектит? 
```
An error has been caught in function '__paginator', process 'MainProcess' (1367571), thread 'MainThread' (140401577594880):
Traceback (most recent call last):

  File "/home/ksv2/rep/parser_avito/parser_cls.py", line 319, in <module>
    ).parse()

  File "/home/ksv2/rep/parser_avito/parser_cls.py", line 271, in parse
    self.__paginator()
    -> <__main__.AvitoParse object at 0x7fb1c7840e80>

> File "/home/ksv2/rep/parser_avito/parser_cls.py", line 54, in __paginator
    self.__parse_page()
    -> <__main__.AvitoParse object at 0x7fb1c7840e80>

  File "/home/ksv2/rep/parser_avito/parser_cls.py", line 90, in __parse_page
    price = title.find_element(*LocatorAvito.PRICE).get_attribute("content")
            |     |             |            -> ('css selector', "[itemprop='price']")
            |     |             -> <class 'locator.LocatorAvito'>
            |     -> <function WebElement.find_element at 0x7fb1c8200280>
            -> <seleniumbase.undetected.webelement.WebElement (session="3481221ffeba998e119a3899a019110d", element="3EA081E033BECD52D45F3529...

  File "/home/ksv2/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 178, in get_attribute
    attribute_value = self.parent.execute_script(
                      |    -> <property object at 0x7fb1c82124d0>
                      -> <seleniumbase.undetected.webelement.WebElement (session="3481221ffeba998e119a3899a019110d", element="3EA081E033BECD52D45F3529...
  File "/home/ksv2/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 408, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           |    |       |                   |               -> [<seleniumbase.undetected.webelement.WebElement (session="3481221ffeba998e119a3899a019110d", element="3EA081E033BECD52D45F352...
           |    |       |                   -> '/* getAttribute */return (function(){return (function(){var h=this||self;function aa(a){return"string"==typeof a}function ba...
           |    |       -> 'w3cExecuteScript'
           |    -> <function WebDriver.execute at 0x7fb1c8202b90>
           -> <seleniumbase.undetected.Chrome (session="3481221ffeba998e119a3899a019110d")>
  File "/home/ksv2/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
    |    |             |              -> {'status': 500, 'value': '{"value":{"error":"script timeout","message":"script timeout\\n  (Session info: chrome=121.0.6167.1...
    |    |             -> <function ErrorHandler.check_response at 0x7fb1c81f1870>
    |    -> <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb1c7939030>
    -> <seleniumbase.undetected.Chrome (session="3481221ffeba998e119a3899a019110d")>
  File "/home/ksv2/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
          |               |        |       -> ['#0 0x56022ba88d93 <unknown>', '#1 0x56022b76c177 <unknown>', '#2 0x56022b7fa184 <unknown>', '#3 0x56022b7da442 <unknown>', ...
          |               |        -> None
          |               -> 'script timeout\n  (Session info: chrome=121.0.6167.139)'
          -> <class 'selenium.common.exceptions.TimeoutException'>

selenium.common.exceptions.TimeoutException: Message: script timeout
  (Session info: chrome=121.0.6167.139)
Stacktrace:
#0 0x56022ba88d93 <unknown>
#1 0x56022b76c177 <unknown>
#2 0x56022b7fa184 <unknown>
#3 0x56022b7da442 <unknown>
#4 0x56022b7f912d <unknown>
#5 0x56022b7da1e3 <unknown>
#6 0x56022b7aa135 <unknown>
#7 0x56022b7ab13e <unknown>
#8 0x56022ba4ce4b <unknown>
#9 0x56022ba50dfa <unknown>
#10 0x56022ba396d5 <unknown>
#11 0x56022ba51a6f <unknown>
#12 0x56022ba1d69f <unknown>
#13 0x56022ba76098 <unknown>
#14 0x56022ba76262 <unknown>
#15 0x56022ba87f34 <unknown>
#16 0x7f32ece94ac3 <unknown>
```

**Comment by Duff89** [comment]
Главное, что парсер продолжает работу

**Comment by Onefabis** [comment]
Поставьте старую версию хрома 115 или пользовательскую версию (ссылка гуглится) или версию для разработчика, и добавить в переменные среды путь до chrome.exe

**Comment by Duff89** [comment]
Закрываю в связи с выходом новой версии
