### ISSUE TITLE
ошибка с получение тестового сообщения в тг бота

### ISSUE THREAD

**Issue by sadgarden** [Duff89/parser_avito#49]
2024-03-13 19:20:00.006 | SUCCESS  | __main__:telegram_log_test:164 - test
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\notifiers\logging.py", line 50, in emit
    self.provider.notify(raise_on_errors=True, **data)
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\notifiers\core.py", line 306, in notify
    rsp.raise_on_errors()
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\notifiers\core.py", line 60, in raise_on_errors
    raise NotificationError(
notifiers.exceptions.NotificationError: Notification errors: Bad Request: chat not found
Call stack:
  File "c:\Users\Admin001\Documents\ccode\parser_avito-master\AvitoParser.py", line 331, in <module>
    Window().mainloop()
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 165, in mainloop
    super().mainloop(*args, **kwargs)
  File "C:\Users\Admin001\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1504, in mainloop
    self.tk.mainloop(n)
  File "C:\Users\Admin001\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\Admin001\Documents\ccode\parser_avito-master\AvitoParser.py", line 164, in telegram_log_test
    logger.success('test')
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\loguru\_logger.py", line 2018, in success
    __self._log("SUCCESS", False, __self._options, __message, args, kwargs)
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\loguru\_logger.py", line 2002, in _log
    handler.emit(log_record, level_id, from_decorator, raw, colored_message)
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\loguru\_handler.py", line 197, in emit
    self._sink.write(str_record)
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\loguru\_simple_sinks.py", line 50, in write
    self._handler.handle(record)
  File "C:\Users\Admin001\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "C:\Users\Admin001\Documents\ccode\parser_avito-master\venv\Lib\site-packages\notifiers\logging.py", line 52, in emit
    self.handleError(record)
Message: 'test'
Arguments: ()
2024-03-13 19:20:03.737 | INFO     | __main__:telegram_log_test:166 - Если сообщение пришло к Вам в telegram - значит всё настроено правильно. Если нет - результат парсинга всегда можно посмотреть в папке result или ниже

**Comment by Duff89** [comment]
notifiers.exceptions.NotificationError: Notification errors: Bad Request: chat not found

**Comment by Duff89** [comment]
Вот кстати видеоинструкция: https://youtu.be/OjId94hYWnc?si=lfDUw1shX_m2NdCS&t=180
